### ISSUE TITLE
When you enter a value into a cell in Firefox, the symbol is duplicated

### ISSUE THREAD

**Issue by ekranis** [myliang/x-spreadsheet#551]
Hello.
When you enter a value into a cell in Firefox, the symbol is duplicated

FireFox 95.0.2

**Comment by HondryTravis** [comment]
used latest version ？

**Comment by ekranis** [comment]
x-data-spreadsheet@1.1.9

**Comment by ekranis** [comment]
on version FireFox 98, the problem is gone.

**Comment by codeconscious** [comment]
Hello. I'm using Firefox 98.0 (64-bit) as well, but this issue is still present for me.

To clarify the issue a bit more: When a single character is typed into an empty cell using Firefox, about 80–90% of the time, the character is doubled (i.e., if you press the "f" key, "ff" will be entered into the cell). This only occurs for the first character, though; subsequent characters are entered normally.

However, I don't believe I'm using version 1.1.9. I see that the latest release version is 1.1.7 from 2020, and I believe I'm using that version. Is 1.1.9 a development version? (If so, is a release forthcoming?)

**Comment by HondryTravis** [comment]
@codeconscious okay, will fix this later, which platform? window/macos

**Comment by codeconscious** [comment]
Just FYI, I've confirmed the issue in the same version of Firefox on Mac OS too. Thanks.

**Comment by codeconscious** [comment]
Yes, I've also only seen the issue in Firefox. I can confirm that Chrome and Edge on Windows are fine too.
